version: '3'
services:
    jenkins:
        build : "."
        restart: always
        container_name: Jenkins
        environment:
            - 'JENKINS_HOME=/var/jenkins_home'
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - '/home/talhatahir/jenkins_home/:/var/jenkins_home'
    sonarqube:
        image: sonarqube
        container_name: SonarQube
        restart: always
        depends_on:
            - postgres
        environment:
            - 'SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/'
            - 'SONAR_JDBC_USERNAME=sonar'
            - 'SONAR_JDBC_PASSWORD=admin1sonar'
        ports:
            - '8082:9000'
        volumes:
            - /home/talhatahir/sonarqube/logs:/opt/sonarqube/logs
            - /home/talhatahir/sonarqube/conf:/opt/sonarqube/conf
            - /home/talhatahir/sonarqube/opt/sonarqube/data:/opt/sonarqube/data
            - /home/talhatahir/sonarqube/opt/sonarqube/extensions:/opt/sonarqube/extensions
    postgres:
        image: 'postgres:latest'
        container_name: PostGres
        restart: always
        environment:
            - 'POSTGRES_USER=sonar'
            - 'POSTGRES_PASSWORD=admin1sonar'
        volumes:
            - '/home/talhatahir/postgresql:/var/lib/postgresql'
            - '/home/talhatahir/postgresql_data:/var/lib/postgresql/data'
